import os
import uuid

from dotenv import load_dotenv
from git import Repo
from github import Github

load_dotenv()


# ============================================================
# Deployment Repository
# ============================================================

DEPLOYMENT_REPO = os.getenv("DEPLOYMENT_REPO")

if not DEPLOYMENT_REPO:
    raise ValueError(
        "DEPLOYMENT_REPO is not configured in .env"
    )

DEPLOYMENT_REPO = os.path.abspath(
    os.path.expandvars(
        os.path.expanduser(DEPLOYMENT_REPO)
    )
)


TERRAFORM_ROOT = os.path.join(
    DEPLOYMENT_REPO,
    "terraform",
    "deployments",
)


# ============================================================
# GitHub Configuration
# ============================================================

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_OWNER = os.getenv("GITHUB_OWNER")
GITHUB_REPO = os.getenv("GITHUB_REPO")

DEV_BRANCH = "dev"
MAIN_BRANCH = "main"


# ============================================================
# Debug Configuration
# ============================================================

print("=" * 60)
print("DEPLOYMENT CONFIGURATION")
print("Deployment Repository :", DEPLOYMENT_REPO)
print("Terraform Root        :", TERRAFORM_ROOT)
print("Repository Exists     :", os.path.exists(DEPLOYMENT_REPO))
print("Terraform Root Exists :", os.path.exists(TERRAFORM_ROOT))
print("=" * 60)


# ============================================================
# Create / Reuse Pull Request
# ============================================================

def create_pull_request():

    github = Github(GITHUB_TOKEN)

    repo = github.get_repo(
        f"{GITHUB_OWNER}/{GITHUB_REPO}"
    )

    # Check whether an open PR already exists
    pulls = repo.get_pulls(
        state="open",
        head=f"{GITHUB_OWNER}:{DEV_BRANCH}",
        base=MAIN_BRANCH,
    )

    if pulls.totalCount > 0:

        existing_pr = pulls[0]

        print(
            f"Using existing PR #{existing_pr.number}"
        )

        return {
            "pr_number": existing_pr.number,
            "pr_url": existing_pr.html_url,
        }

    # Create new PR
    pr = repo.create_pull(
        title="Terraform Deployment",
        body=(
            "Terraform generated by "
            "Cloud Infrastructure AI Agent."
        ),
        head=DEV_BRANCH,
        base=MAIN_BRANCH,
    )

    print(
        f"Created new PR #{pr.number}"
    )

    return {
        "pr_number": pr.number,
        "pr_url": pr.html_url,
    }


# ============================================================
# Save Generated Terraform
# ============================================================

def save_generated_code(
    thread_id: str,
    generated_code: dict,
):

    deployment_id = str(uuid.uuid4())

    print("=" * 60)
    print("STARTING DEPLOYMENT GENERATION")
    print("Deployment ID:", deployment_id)
    print("=" * 60)

    # --------------------------------------------------------
    # Verify deployment repository
    # --------------------------------------------------------

    if not os.path.exists(DEPLOYMENT_REPO):

        raise FileNotFoundError(
            f"Deployment repository does not exist: "
            f"{DEPLOYMENT_REPO}"
        )

    # --------------------------------------------------------
    # Open deployment Git repository
    # --------------------------------------------------------

    repo = Repo(DEPLOYMENT_REPO)

    origin = repo.remote("origin")

    # --------------------------------------------------------
    # Fetch latest branches
    # --------------------------------------------------------

    print("Fetching latest branches...")

    origin.fetch()

    # --------------------------------------------------------
    # Checkout / Create dev branch
    # --------------------------------------------------------

    remote_branches = [
        ref.name
        for ref in origin.refs
    ]

    if f"origin/{DEV_BRANCH}" in remote_branches:

        print(
            "Checking out existing dev branch..."
        )

        repo.git.checkout(DEV_BRANCH)

        origin.pull(DEV_BRANCH)

    else:

        print(
            "Creating dev branch..."
        )

        repo.git.checkout(MAIN_BRANCH)

        origin.pull(MAIN_BRANCH)

        repo.git.checkout(
            "-b",
            DEV_BRANCH,
        )

        repo.git.push(
            "--set-upstream",
            "origin",
            DEV_BRANCH,
        )

    # --------------------------------------------------------
    # Create deployment folder
    # --------------------------------------------------------

    deployment_folder = os.path.join(
        TERRAFORM_ROOT,
        deployment_id,
    )

    print("=" * 60)
    print("DEPLOYMENT FOLDER")
    print(deployment_folder)
    print("=" * 60)

    os.makedirs(
        deployment_folder,
        exist_ok=True,
    )

    # --------------------------------------------------------
    # Write Terraform files
    # --------------------------------------------------------

    for filename, content in generated_code.items():

        filepath = os.path.join(
            deployment_folder,
            filename,
        )

        # Prevent nested directories from causing errors
        os.makedirs(
            os.path.dirname(filepath),
            exist_ok=True,
        )

        with open(
            filepath,
            "w",
            encoding="utf-8",
        ) as file:

            file.write(content)

        print(
            "Created:",
            filepath,
        )

    # --------------------------------------------------------
    # Commit
    # --------------------------------------------------------

    repo.git.add(A=True)

    if repo.is_dirty(
        untracked_files=True
    ):

        repo.index.commit(
            f"Generated Terraform ({deployment_id})"
        )

        print(
            f"Committed deployment {deployment_id}"
        )

    else:

        print(
            "Nothing new to commit."
        )

    # --------------------------------------------------------
    # Push
    # --------------------------------------------------------

    origin.push(DEV_BRANCH)

    print(
        f"Pushed deployment {deployment_id} "
        f"to {DEV_BRANCH}"
    )

    # --------------------------------------------------------
    # Create / Reuse PR
    # --------------------------------------------------------

    pr = create_pull_request()

    print("=" * 60)
    print("DEPLOYMENT COMPLETE")
    print("Deployment ID :", deployment_id)
    print("Branch        :", DEV_BRANCH)
    print("PR Number     :", pr["pr_number"])
    print("PR URL        :", pr["pr_url"])
    print("Local Folder  :", deployment_folder)
    print("=" * 60)

    return {
        "deployment_id": deployment_id,
        "branch_name": DEV_BRANCH,
        "pr_number": pr["pr_number"],
        "pr_url": pr["pr_url"],
    }