import os
import uuid

from dotenv import load_dotenv
from git import Repo, GitCommandError
from github import Github

load_dotenv()

DEPLOYMENT_REPO = os.getenv("DEPLOYMENT_REPO")

if not DEPLOYMENT_REPO:
    raise ValueError("DEPLOYMENT_REPO is not configured in .env")

TERRAFORM_ROOT = os.path.join(
    DEPLOYMENT_REPO,
    "terraform",
    "deployments",
)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GITHUB_OWNER = os.getenv("GITHUB_OWNER")
GITHUB_REPO = os.getenv("GITHUB_REPO")

DEV_BRANCH = "dev"
MAIN_BRANCH = "main"


def create_pull_request():

    github = Github(GITHUB_TOKEN)

    repo = github.get_repo(f"{GITHUB_OWNER}/{GITHUB_REPO}")

    # Check if a PR already exists
    pulls = repo.get_pulls(
        state="open",
        head=f"{GITHUB_OWNER}:{DEV_BRANCH}",
        base=MAIN_BRANCH,
    )

    if pulls.totalCount > 0:
        existing_pr = pulls[0]

        return {
            "pr_number": existing_pr.number,
            "pr_url": existing_pr.html_url,
            }

    pr = repo.create_pull(
        title="Terraform Deployment",
        body="Terraform generated by Cloud Infra AI Agent.",
        head=DEV_BRANCH,
        base=MAIN_BRANCH,
    )

    return {
    "pr_number": pr.number,
    "pr_url": pr.html_url
            }


def save_generated_code(thread_id: str, generated_code: dict):

    deployment_id = str(uuid.uuid4())

    repo = Repo(DEPLOYMENT_REPO)

    origin = repo.remote("origin")

    print("Fetching latest branches...")
    origin.fetch()

    # -----------------------------
    # Checkout/Create dev branch
    # -----------------------------
    remote_branches = [ref.name for ref in origin.refs]

    if f"origin/{DEV_BRANCH}" in remote_branches:

        print("Checking out existing dev branch...")

        repo.git.checkout(DEV_BRANCH)

        origin.pull(DEV_BRANCH)

    else:

        print("Creating dev branch...")

        repo.git.checkout(MAIN_BRANCH)

        origin.pull(MAIN_BRANCH)

        repo.git.checkout("-b", DEV_BRANCH)

        repo.git.push("--set-upstream", "origin", DEV_BRANCH)

    # -----------------------------
    # Write Terraform
    # -----------------------------

    deployment_folder = os.path.join(
        TERRAFORM_ROOT,
        deployment_id,
    )

    os.makedirs(deployment_folder, exist_ok=True)

    for filename, content in generated_code.items():

        filepath = os.path.join(
            deployment_folder,
            filename,
        )

        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)

    # -----------------------------
    # Commit
    # -----------------------------

    repo.git.add(A=True)

    try:

        repo.index.commit(
            f"Generated Terraform ({deployment_id})"
        )

    except Exception:

        print("Nothing new to commit.")

    # -----------------------------
    # Push
    # -----------------------------

    origin.push(DEV_BRANCH)

    # -----------------------------
    # Create / Reuse Pull Request
    # -----------------------------

    #pr_url = create_pull_request()

    print("=" * 60)
    print("Deployment ID :", deployment_id)
    print("Branch        :", DEV_BRANCH)
    #print("PR URL        :", pr_url)
    print("=" * 60)

    pr = create_pull_request()

    return {
    "deployment_id": deployment_id,
    "branch_name": DEV_BRANCH,
    "pr_number": pr["pr_number"],
    "pr_url": pr["pr_url"],
    }